### PR TITLE
 If we catch the wrong exception in AssertThrows, print the description of the exception

### LINKED ISSUE #47: Show more information if AssertThrows fails
Hello,

it'd be nice if AssertThrows showed more information if it failed instead of just saying that it didn't get the exception it wanted. Maybe it'd be possible to test if the exception can be gotten via std::current_exception and if so get the description of that? I'd like to implement that if you're OK with that.

### PR DESCRIPTION
**Pull request by Cogitri**
This makes it easier to debug the failure

fixes #47

### CODE REVIEW

File: example/exceptions_tests.cpp [hunk 1]
```diff
@@ -89,4 +97,9 @@ void ExceptionTests()
     AssertThrows(AssertionException, LastException<std::logic_error>());
     AssertThat(LastException<AssertionException>().GetMessage(), Contains("No exception was stored"));
   }
+
+  it("prints description of unwanted exception");
+  {
+    AssertTestFails(AssertThrows(ExceptionWeExcepted, objectUnderTest.LogicError()), "Expected ExceptionWeExcepted. Wrong exception was thrown. Description of unwated exception: not logical!");
+  }
 }
```
Comment (sbeyer) [inline example/exceptions_tests.cpp]: Speaking of commit messages: The commit subjects (first line) are way too long. Even GitHub does not display it in full length.

For example, change them to, for example:
* Print description of unexpected exception in AssertThrows
* Test printing unexpected exception in AssertThrows

File: include/snowhouse/exceptions.h [hunk 2]
```diff
@@ -97,6 +99,14 @@ namespace snowhouse
   catch (...) \
   { \
     SNOWHOUSE_TEMPVAR(wrong_exception) = true; \
+    if (auto eptr = std::current_exception()) { \
+      try { \
+      std::rethrow_exception(eptr); \
+      } catch (std::exception& e) { \
+      SNOWHOUSE_TEMPVAR(more_info) = true; \
+      SNOWHOUSE_TEMPVAR(info_string) = e.what(); \
+      } catch (...) {} \
```
Comment (sbeyer) [inline include/snowhouse/exceptions.h]: Indentation has gone wrong here. (This part is not checked by clang-format.)

File: include/snowhouse/exceptions.h [hunk 3]
```diff
@@ -108,6 +118,9 @@ namespace snowhouse
   { \
     ::std::ostringstream SNOWHOUSE_TEMPVAR(stm); \
     SNOWHOUSE_TEMPVAR(stm) << "Expected " #EXCEPTION_TYPE ". Wrong exception was thrown."; \
+    if (SNOWHOUSE_TEMPVAR(more_info)) { \
+      SNOWHOUSE_TEMPVAR(stm) << " Description of unwated exception: " << SNOWHOUSE_TEMPVAR(info_string); \
```
Comment (sbeyer) [inline include/snowhouse/exceptions.h]: Typo "unwated" (missing n)

File: include/snowhouse/exceptions.h [hunk 4]
```diff
@@ -85,6 +85,8 @@ namespace snowhouse
   SNOWHOUSE_TEMPVAR(storage).compiler_thinks_i_am_unused(); \
   bool SNOWHOUSE_TEMPVAR(wrong_exception) = false; \
   bool SNOWHOUSE_TEMPVAR(no_exception) = false; \
+  bool SNOWHOUSE_TEMPVAR(more_info) = true; \
+  std::string SNOWHOUSE_TEMPVAR(info_string) = ""; \
```
Comment (sbeyer) [inline include/snowhouse/exceptions.h]: The assignment `= ""` is not necessary for initialization. (Matter of taste probably.)

File: include/snowhouse/exceptions.h [hunk 5]
```diff
@@ -97,6 +99,14 @@ namespace snowhouse
   catch (...) \
   { \
     SNOWHOUSE_TEMPVAR(wrong_exception) = true; \
+    if (auto eptr = std::current_exception()) { \
+      try { \
+      std::rethrow_exception(eptr); \
+      } catch (std::exception& e) { \
```
Comment (sbeyer) [inline include/snowhouse/exceptions.h]: Another nitpicking, but please add `const`

File: example/exceptions_tests.cpp [hunk 6]
```diff
@@ -26,6 +26,14 @@ struct ClassWithExceptions
   }
 };
 
+struct ExceptionWeExcepted : public std::exception
```
[the remark this answers is not in the document]
Comment (sbeyer) [reply example/exceptions_tests.cpp]: Probably even better is the name `ExpectedException`, isn't it? Or does that sound too much like an exception about "expected" stuff? Well, I don't care much.

File: include/snowhouse/exceptions.h (hunk 2 above)
Comment (Cogitri) [reply include/snowhouse/exceptions.h]: Oh right, somehow I stopped paying attention to that since clang-format always deals with that for me otherwise

File: include/snowhouse/exceptions.h (hunk 4 above)
Comment (Cogitri) [reply include/snowhouse/exceptions.h]: I personally prefer it for clarity but I don't mind removing it.

**Comment by Cogitri** [comment]
Pushed a new version, sorry for the typos, seems like I was a bit sidetracked yesterday :)

File: include/snowhouse/exceptions.h (hunk 2 above)
Comment (sbeyer) [reply include/snowhouse/exceptions.h]: Unfortunately I didn't get clang-format to handle multiline macro definitions as I like them, so it's turned off for those sections.

Comment (Cogitri) [reply include/snowhouse/exceptions.h]: Ah okay :)

File: include/snowhouse/exceptions.h (hunk 4 above)
Comment (sbeyer) [reply include/snowhouse/exceptions.h]: Yes, as I said, it's a matter of taste, and I clearly prefer using the default constructor over some other constructor if possible.

Comment (Cogitri) [reply include/snowhouse/exceptions.h]: Yup, changed that already.
